[package]
name = "conver_hour_to_seconds"
version = "0.1.0"
authors = ["Jeferson 'Shin' <shin.jef@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
