extends Node

const sounds = {
	"a": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_a.wav"),
	"b": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_b.wav"),
	"c": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_c.wav"),
	"d": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_d.wav"),
	"e": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_e.wav"),
	"f": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_f.wav"),
	"g": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_g.wav"),
	"h": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_a.wav"),
	"i": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_b.wav"),
	"j": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_c.wav"),
	"k": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_d.wav"),
	"l": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_e.wav"),
	"m": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_f.wav"),
	"n": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_g.wav"),
	"o": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_a.wav"),
	"p": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_b.wav"),
	"q": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_c.wav"),
	"r": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_d.wav"),
	"s": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_e.wav"),
	"t": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_f.wav"),
	"u": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_g.wav"),
	"v": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_a.wav"),
	"w": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_b.wav"),
	"x": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_c.wav"),
	"y": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_d.wav"),
	"z": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_e.wav"),
	"th": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_f.wav"),
	"sh": preload("res://Entities/TextToVoice/Voices/AcuteSoftVoice/4_g.wav"),
	" ": preload("res://Entities/TextToVoice/Voices/BlankVoice/blank.wav"),
	".": preload("res://Entities/TextToVoice/Voices/BlankVoice/longblank.wav")
}
