GET http://localhost:3000/account HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/account HTTP/1.1
Content-Type: application/json

{
  "firstName": "Shin",
  "lastName": "Spiegel"
}

###

GET http://localhost:3000/account/40 HTTP/1.1
Content-Type: application/json

###

DELETE http://localhost:3000/account/3 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/account HTTP/1.1
Content-Type: application/json

{
  "toAccount": 1,
  "amount": 100
}

###