extends Node

const sounds = {
	"a": preload("res://Entities/TextToVoice/Voices/OriginalVoice/a.wav"),
	"b": preload("res://Entities/TextToVoice/Voices/OriginalVoice/b.wav"),
	"c": preload("res://Entities/TextToVoice/Voices/OriginalVoice/c.wav"),
	"d": preload("res://Entities/TextToVoice/Voices/OriginalVoice/d.wav"),
	"e": preload("res://Entities/TextToVoice/Voices/OriginalVoice/e.wav"),
	"f": preload("res://Entities/TextToVoice/Voices/OriginalVoice/f.wav"),
	"g": preload("res://Entities/TextToVoice/Voices/OriginalVoice/g.wav"),
	"h": preload("res://Entities/TextToVoice/Voices/OriginalVoice/h.wav"),
	"i": preload("res://Entities/TextToVoice/Voices/OriginalVoice/i.wav"),
	"j": preload("res://Entities/TextToVoice/Voices/OriginalVoice/j.wav"),
	"k": preload("res://Entities/TextToVoice/Voices/OriginalVoice/k.wav"),
	"l": preload("res://Entities/TextToVoice/Voices/OriginalVoice/l.wav"),
	"m": preload("res://Entities/TextToVoice/Voices/OriginalVoice/m.wav"),
	"n": preload("res://Entities/TextToVoice/Voices/OriginalVoice/n.wav"),
	"o": preload("res://Entities/TextToVoice/Voices/OriginalVoice/o.wav"),
	"p": preload("res://Entities/TextToVoice/Voices/OriginalVoice/p.wav"),
	"q": preload("res://Entities/TextToVoice/Voices/OriginalVoice/q.wav"),
	"r": preload("res://Entities/TextToVoice/Voices/OriginalVoice/r.wav"),
	"s": preload("res://Entities/TextToVoice/Voices/OriginalVoice/s.wav"),
	"t": preload("res://Entities/TextToVoice/Voices/OriginalVoice/t.wav"),
	"u": preload("res://Entities/TextToVoice/Voices/OriginalVoice/u.wav"),
	"v": preload("res://Entities/TextToVoice/Voices/OriginalVoice/v.wav"),
	"w": preload("res://Entities/TextToVoice/Voices/OriginalVoice/w.wav"),
	"x": preload("res://Entities/TextToVoice/Voices/OriginalVoice/x.wav"),
	"y": preload("res://Entities/TextToVoice/Voices/OriginalVoice/y.wav"),
	"z": preload("res://Entities/TextToVoice/Voices/OriginalVoice/z.wav"),
	"th": preload("res://Entities/TextToVoice/Voices/OriginalVoice/th.wav"),
	"sh": preload("res://Entities/TextToVoice/Voices/OriginalVoice/sh.wav"),
	" ": preload("res://Entities/TextToVoice/Voices/OriginalVoice/blank.wav"),
	".": preload("res://Entities/TextToVoice/Voices/OriginalVoice/longblank.wav")
}
