[package]
name = "flycheck"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
authors = ["rust-analyzer developers"]
edition = "2018"

[lib]
doctest = false

[dependencies]
crossbeam-channel = "0.5.0"
log = "0.4.8"
cargo_metadata = "0.12.2"
serde_json = "1.0.48"
jod-thread = "0.1.1"

toolchain = { path = "../toolchain", version = "0.0.0" }
stdx = { path = "../stdx", version = "0.0.0"  }
