extends Node2D

var hero_voice = {
	'a': load("res://assets/voices/test_voice/a.wav"),
	'b': load('res://assets/voices/test_voice/b.wav'),
	'c': load('res://assets/voices/test_voice/c.wav'),
	'd': load('res://assets/voices/test_voice/d.wav'),
	'e': load('res://assets/voices/test_voice/e.wav'),
	'f': load('res://assets/voices/test_voice/f.wav'),
	'g': load('res://assets/voices/test_voice/g.wav'),
	'h': load('res://assets/voices/test_voice/h.wav'),
	'i': load('res://assets/voices/test_voice/i.wav'),
	'j': load('res://assets/voices/test_voice/j.wav'),
	'k': load('res://assets/voices/test_voice/k.wav'),
	'l': load('res://assets/voices/test_voice/l.wav'),
	'm': load('res://assets/voices/test_voice/m.wav'),
	'n': load('res://assets/voices/test_voice/n.wav'),
	'o': load('res://assets/voices/test_voice/o.wav'),
	'p': load('res://assets/voices/test_voice/p.wav'),
	'q': load('res://assets/voices/test_voice/q.wav'),
	'r': load('res://assets/voices/test_voice/r.wav'),
	's': load('res://assets/voices/test_voice/s.wav'),
	't': load('res://assets/voices/test_voice/t.wav'),
	'u': load('res://assets/voices/test_voice/u.wav'),
	'v': load('res://assets/voices/test_voice/v.wav'),
	'w': load('res://assets/voices/test_voice/w.wav'),
	'x': load('res://assets/voices/test_voice/x.wav'),
	'y': load('res://assets/voices/test_voice/y.wav'),
	'z': load('res://assets/voices/test_voice/z.wav'),
	'th': load('res://assets/voices/test_voice/th.wav'),
	'sh': load('res://assets/voices/test_voice/sh.wav'),
	' ': load('res://assets/voices/test_voice/blank.wav'),
	'.': load('res://assets/voices/test_voice/longblank.wav')
}

var vampire_voice = {
	'a': load("res://assets/voices/test_voice/a.wav"),
	'b': load('res://assets/voices/test_voice/b.wav'),
	'c': load('res://assets/voices/test_voice/c.wav'),
	'd': load('res://assets/voices/test_voice/d.wav'),
	'e': load('res://assets/voices/test_voice/e.wav'),
	'f': load('res://assets/voices/test_voice/f.wav'),
	'g': load('res://assets/voices/test_voice/g.wav'),
	'h': load('res://assets/voices/test_voice/h.wav'),
	'i': load('res://assets/voices/test_voice/i.wav'),
	'j': load('res://assets/voices/test_voice/j.wav'),
	'k': load('res://assets/voices/test_voice/k.wav'),
	'l': load('res://assets/voices/test_voice/l.wav'),
	'm': load('res://assets/voices/test_voice/m.wav'),
	'n': load('res://assets/voices/test_voice/n.wav'),
	'o': load('res://assets/voices/test_voice/o.wav'),
	'p': load('res://assets/voices/test_voice/p.wav'),
	'q': load('res://assets/voices/test_voice/q.wav'),
	'r': load('res://assets/voices/test_voice/r.wav'),
	's': load('res://assets/voices/test_voice/s.wav'),
	't': load('res://assets/voices/test_voice/t.wav'),
	'u': load('res://assets/voices/test_voice/u.wav'),
	'v': load('res://assets/voices/test_voice/v.wav'),
	'w': load('res://assets/voices/test_voice/w.wav'),
	'x': load('res://assets/voices/test_voice/x.wav'),
	'y': load('res://assets/voices/test_voice/y.wav'),
	'z': load('res://assets/voices/test_voice/z.wav'),
	'th': load('res://assets/voices/test_voice/th.wav'),
	'sh': load('res://assets/voices/test_voice/sh.wav'),
	' ': load('res://assets/voices/test_voice/blank.wav'),
	'.': load('res://assets/voices/test_voice/longblank.wav')
}

var default_voice = {
	'a': load("res://assets/voices/test_voice/a.wav"),
	'b': load('res://assets/voices/test_voice/b.wav'),
	'c': load('res://assets/voices/test_voice/c.wav'),
	'd': load('res://assets/voices/test_voice/d.wav'),
	'e': load('res://assets/voices/test_voice/e.wav'),
	'f': load('res://assets/voices/test_voice/f.wav'),
	'g': load('res://assets/voices/test_voice/g.wav'),
	'h': load('res://assets/voices/test_voice/h.wav'),
	'i': load('res://assets/voices/test_voice/i.wav'),
	'j': load('res://assets/voices/test_voice/j.wav'),
	'k': load('res://assets/voices/test_voice/k.wav'),
	'l': load('res://assets/voices/test_voice/l.wav'),
	'm': load('res://assets/voices/test_voice/m.wav'),
	'n': load('res://assets/voices/test_voice/n.wav'),
	'o': load('res://assets/voices/test_voice/o.wav'),
	'p': load('res://assets/voices/test_voice/p.wav'),
	'q': load('res://assets/voices/test_voice/q.wav'),
	'r': load('res://assets/voices/test_voice/r.wav'),
	's': load('res://assets/voices/test_voice/s.wav'),
	't': load('res://assets/voices/test_voice/t.wav'),
	'u': load('res://assets/voices/test_voice/u.wav'),
	'v': load('res://assets/voices/test_voice/v.wav'),
	'w': load('res://assets/voices/test_voice/w.wav'),
	'x': load('res://assets/voices/test_voice/x.wav'),
	'y': load('res://assets/voices/test_voice/y.wav'),
	'z': load('res://assets/voices/test_voice/z.wav'),
	'th': load('res://assets/voices/test_voice/th.wav'),
	'sh': load('res://assets/voices/test_voice/sh.wav'),
	' ': load('res://assets/voices/test_voice/blank.wav'),
	'.': load('res://assets/voices/test_voice/longblank.wav')
}
