version: "3.7"

services:
  express:
    build: ./services/express
    command: npm start
    volumes:
      - ./services/express:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.express
